#!/bin/bash
#
# Post push hook for Docker Automated Build.
#
# This hook simply adds the 'latest' tag to the image.

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "Image built:
    IMAGE_NAME=$IMAGE_NAME
    DOCKER_REPO=$DOCKER_REPO
    DOCKER_TAG=$DOCKER_TAG
"

if [ "$DOCKER_TAG" = "latest" ]; then
    echo "Image already have the 'latest' tag."
    DOCKER_NEWTAG=
elif [[ "$DOCKER_TAG" =~ -beta[0-9.]*$ ]]; then
    DOCKER_NEWTAG="beta"
else
    DOCKER_NEWTAG="latest"
fi

if [ -n "$DOCKER_NEWTAG" ]; then
    echo "Adding tag '$DOCKER_NEWTAG' to image..."
    docker tag $IMAGE_NAME ${DOCKER_REPO}:$DOCKER_NEWTAG
    echo "Pushing image..."
    docker push ${DOCKER_REPO}:$DOCKER_NEWTAG
fi

echo "post_push hook terminated successfully."
